### ISSUE TITLE
Test failing because package.json and package-lock.json not in sync

### ISSUE THREAD

**Issue by stropitek** [cheminfo-js/peptide#1]
@lpatiny 
Tests are failing on node 10 because travis uses `npm ci` for installing packages, which enforces that your `package.json` and `package-lock.json` files be in sync.
You should rerun `npm install` and push the new `package-lock.json`

**Comment by lpatiny** [comment]
Thanks it was done 041c8d080261bedac7196bfb8b9cc0d84bc8ef0d
